services:
  mock-db:
      image: postgres:17
      restart: always
      ports:
        - "5432:5432"
      env_file:
        - .mock-db/.env
      volumes:
        - ./mock-db/init.sql:/docker-entrypoint-initdb.d/init.sql
        - mock-db:/var/lib/postgresql/data

  neo4j:
      image: neo4j:5.11
      ports:
        - "7687:7687"
        - "7474:7474"
      volumes:
        - ./neo4j/data:/data
      environment:
        - NEO4J_PLUGINS=["apoc"]
        - NEO4J_db_tx__log_rotation_retention__policy=false
        - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      env_file:
        - ./neo4j/.env
      healthcheck:
          test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider localhost:7474 || exit 1"]
          interval: 15s
          timeout: 30s
          retries: 10
      networks:
        - net