# Generated by Django 5.1.3 on 2024-11-17 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('db_configurator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=2500)),
                ('type', models.CharField(choices=[('BAR', 'BAR_CHART'), ('LINE', 'LINE_CHART'), ('BUBBLE', 'BUBBLE_CHART'), ('HISTOGRAM', 'HISTOGRAM'), ('SCATTER', 'SCATTER_CHART'), ('PIE', 'PIE_CHART'), ('TABLE', 'TABLE')], max_length=100)),
                ('sql_query', models.TextField()),
                ('meta_data', models.JSONField()),
                ('data_source_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_configurator.databasesource')),
            ],
        ),
    ]
