# Generated by Django 5.1.3 on 2024-11-17 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporter_agent', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chart',
            old_name='data_source_id',
            new_name='data_source',
        ),
    ]
