# Generated by Django 5.1.3 on 2024-11-24 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter_agent', '0002_rename_data_source_id_chart_data_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
