# Generated by Django 5.1.4 on 2024-12-26 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter_agent', '0003_alter_chart_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='meta_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
