# Generated by Django 5.1.7 on 2025-03-15 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter_agent', '0006_alter_chart_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenAIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('host', models.CharField(max_length=200, null=True)),
                ('active', models.BooleanField(default=False)),
                ('api_key', models.TextField()),
            ],
        ),
    ]
