# Generated by Django 5.1.1 on 2025-03-31 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter_agent', '0007_genaimodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='chart_img_url',
            field=models.TextField(null=True),
        ),
    ]
