# Generated by Django 5.0.6 on 2024-11-10 14:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='conversation_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
