# Generated by Django 5.1.5 on 2025-01-26 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_remove_message_conversation_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='title',
            field=models.CharField(default='Example', max_length=300),
            preserve_default=False,
        ),
    ]
