# Generated by Django 5.1.1 on 2025-06-29 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_conversation_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='status',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='status_desc',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
