# Generated by Django 5.1.3 on 2024-11-17 15:32

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=2500)),
                ('user_id', models.IntegerField(verbose_name=django.contrib.auth.models.User)),
            ],
        ),
        migrations.CreateModel(
            name='DashboardSlot',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('row_num', models.IntegerField()),
                ('col_num', models.IntegerField()),
            ],
        ),
    ]
