# Generated by Django 5.1.3 on 2024-11-17 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0001_initial'),
        ('reporter_agent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardslot',
            name='chart_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reporter_agent.chart'),
        ),
        migrations.AddField(
            model_name='dashboardslot',
            name='dashboard_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.dashboard'),
        ),
    ]
