# Generated by Django 5.1.3 on 2024-11-17 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dashboard',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='dashboardslot',
            old_name='chart_id',
            new_name='chart',
        ),
        migrations.RenameField(
            model_name='dashboardslot',
            old_name='dashboard_id',
            new_name='dashboard',
        ),
    ]
