# Generated by Django 5.1.3 on 2024-12-16 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_dashboard_id_alter_dashboardslot_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardslot',
            name='height',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dashboardslot',
            name='width',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
