# Generated by Django 5.1.4 on 2024-12-27 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_dashboardslot_height_dashboardslot_width'),
        ('reporter_agent', '0004_alter_chart_meta_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardslot',
            name='chart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporter_agent.chart'),
        ),
    ]
