# Generated by Django 5.1.1 on 2025-07-22 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_dashboardslot_chart'),
        ('reporter_agent', '0008_chart_chart_img_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardslot',
            name='chart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reporter_agent.chart'),
        ),
    ]
