# Generated by Django 5.1.2 on 2024-10-15 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseSource',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('postgresql', 'postgresql'), ('mssql', 'mssql')], max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('host', models.CharField(max_length=1000)),
                ('port', models.IntegerField()),
            ],
        ),
    ]
