# Generated by Django 5.1.4 on 2024-12-08 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_configurator', '0002_alter_databasesource_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='databasesource',
            name='is_paused',
            field=models.BooleanField(default=False),
        ),
    ]
