# Generated by Django 5.1.3 on 2024-12-14 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('db_configurator', '0004_databasesource_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databasesource',
            name='group',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.group'),
        ),
    ]
