# Generated by Django 5.1.3 on 2024-12-14 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_configurator', '0005_alter_databasesource_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='databasesource',
            name='display_name',
            field=models.CharField(default=None, max_length=300),
            preserve_default=False,
        ),
    ]
