# Generated by Django 5.1.3 on 2024-12-14 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_configurator', '0006_databasesource_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='databasesource',
            name='is_ready',
            field=models.BooleanField(default=False),
        ),
    ]
