# Generated by Django 5.1.3 on 2024-12-14 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_configurator', '0008_remove_databasesource_is_paused_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databasesource',
            name='status',
            field=models.CharField(choices=[('PAUSED', 'PAUSED'), ('LOADING', 'LOADING'), ('READY', 'READY'), ('ERROR', 'ERROR')], default='LOADING', max_length=50),
        ),
    ]
