# Generated by Django 5.1.5 on 2025-03-02 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_configurator', '0009_alter_databasesource_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableDocumentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.CharField(max_length=255)),
                ('table_name', models.CharField(max_length=255)),
                ('documentation', models.JSONField()),
                ('database_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_configurator.databasesource')),
            ],
            options={
                'unique_together': {('database_source', 'schema_name', 'table_name')},
            },
        ),
    ]
