# Generated by Django 5.1.1 on 2025-04-12 10:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_configurator', '0010_tabledocumentation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='databasesource',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='databasesource',
            name='schema_name',
            field=models.CharField(default=None, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='databasesource',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='databasesource',
            name='type',
            field=models.CharField(choices=[('postgresql', 'postgresql'), ('mssql', 'mssql'), ('excel', 'excel')], max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='databasesource',
            unique_together={('host', 'port', 'name', 'schema_name')},
        ),
    ]
