# Generated by Django 5.1.1 on 2025-04-12 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_configurator', '0012_alter_databasesource_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='databasesource',
            name='source_type',
            field=models.CharField(choices=[('excel', 'excel'), ('db', 'db')], default='db', max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='databasesource',
            name='type',
            field=models.CharField(choices=[('postgresql', 'postgresql'), ('mssql', 'mssql')], max_length=50),
        ),
    ]
