# Generated by Django 5.1.1 on 2025-04-12 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_configurator', '0013_databasesource_source_type_alter_databasesource_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databasesource',
            name='source_type',
            field=models.CharField(choices=[('excel', 'excel'), ('db', 'db')], default='db', max_length=1000),
        ),
    ]
